---
- name: Play to check for package status
  hosts: all
  become: true
  tasks:
  - name: To query the git package
    shell: rpm -q git;echo $?
    register: package_check
  - name: To print the results that GIT is installed
    debug:
      msg: "Output: {{ package_check.stdout_lines}}"
    when: package_check.stdout_lines==0

  - name: To print results that GIT is not installed
    debug:
      msg: "Output: {{ package_check.stdout_lines}}"
    when: package_check.stdout_lines!=1
  - name: To install GIT
    shell: yum install git -y
    when: package_check.stdout_lines!=1
